name: nf-fuzzball CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build nf-fuzzball
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Get Fuzzball version on stable
        run: |
          FUZZBALL_VERSION=$(curl -s https://api.stable.fuzzball.ciq.dev/v2/version | jq -r '.version')
          echo "FUZZBALL_VERSION=${FUZZBALL_VERSION}" >> $GITHUB_ENV

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      
      - name: Get plugin version
        run: |
          echo "Getting plugin version from build.gradle"
          PLUGIN_VERSION=$(grep -E "version\s*=" build.gradle | head -1 | sed -E "s/.*version\s*=\s*'([^']+)'.*/\1/")
          echo "PLUGIN_VERSION=${PLUGIN_VERSION}" >> $GITHUB_ENV

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          architecture: x64
          distribution: 'temurin'

      - name: Compile
        run: ./gradlew assemble

      - name: Tests
        run: ./gradlew check
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

