name: nf-fuzzball CI
on:
  pull_request:
    branches:
      - '*'
  push: 
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      publish_release:
        description: 'Publish release (default: false)'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build nf-fuzzball
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Get Fuzzball version on stable
        run: |
          FUZZBALL_VERSION=$(curl -s https://api.stable.fuzzball.ciq.dev/v2/version | jq -r '.version')
          echo "FUZZBALL_VERSION=${FUZZBALL_VERSION}" >> $GITHUB_ENV

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      
      - name: Set plugin version
        run: |

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "Using tag as plugin version"
            PLUGIN_VERSION="${{ github.ref_name }}"
            # Remove the v prefix if it exists
            echo "PLUGIN_VERSION=${PLUGIN_VERSION#v}" >> $GITHUB_ENV
          else
            echo "Not pushing to a tag, using build.gradle to determine plugin version"
            PLUGIN_VERSION=$(grep -E "version\s*=" build.gradle | head -1 | sed -E "s/.*version\s*=\s*'([^']+)'.*/\1/")
            echo "PLUGIN_VERSION=${PLUGIN_VERSION}" >> $GITHUB_ENV
          fi

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          architecture: x64
          distribution: 'temurin'

      - name: Compile
        run: ./gradlew assemble

      - name: Tests
        run: ./gradlew check
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

      - name: Update name of build artifact
        run: |
          echo "Renaming build artifact to nf-fuzzball-${{ env.PLUGIN_VERSION }}-stable-${{ env.FUZZBALL_VERSION }}.zip"
          mv build/distributions/nf-fuzzball-${{ env.PLUGIN_VERSION }}.zip build/distributions/nf-fuzzball-${{ env.PLUGIN_VERSION }}-stable-${{ env.FUZZBALL_VERSION }}.zip

      - name: Create or update release and attach artifact
        if: github.event.inputs.publish_release == 'true' || github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          name: Release v${{ env.PLUGIN_VERSION }}
          tag: v${{ env.PLUGIN_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: "build/distributions/nf-fuzzball-${{ env.PLUGIN_VERSION }}-stable-${{ env.FUZZBALL_VERSION }}.zip"
          artifactContentType: "application/zip"
