name: nf-fuzzball CI
on:
  pull_request:
    branches:
      - '*'
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      publish_release:
        description: 'Publish release (default: false)'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build nf-fuzzball
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Get Fuzzball version on stable (starts with 'v')
        run: |
          FUZZBALL_VERSION=$(curl -s https://api.stable.fuzzball.ciq.dev/v2/version | jq -r '.version')
          # make sure Fuzzball version starts with a v
          echo "FUZZBALL_VERSION=v${FUZZBALL_VERSION#v}" >> $GITHUB_ENV

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Set plugin version (starts with 'v')
        run: |
          # PLUGIN_VERSION always comes from gradle but we make sure it also starts with a v
          PLUGIN_VERSION=$(grep -E "version\s*=" build.gradle | head -1 | sed -E "s/.*version\s*=\s*'([^']+)'.*/\1/")
          echo "PLUGIN_VERSION=v${PLUGIN_VERSION#v}" >> $GITHUB_ENV

      - name: Check plugin in build.gradle matches tag
        if: github.ref_type == 'tag'
        run: |
          PLUGIN_VERSION_TAG="${{ github.ref_name }}"
          PLUGIN_VERSION_GRADLE="${{ env.PLUGIN_VERSION }}"

          if [[ "${PLUGIN_VERSION_TAG#v}" != "${PLUGIN_VERSION_GRADLE#v}" ]]; then
            echo "Plugin version in build.gradle (${PLUGIN_VERSION_GRADLE#v}) does not match tag (${PLUGIN_VERSION_TAG#v})"
            exit 1
          else
            echo "Plugin version in build.gradle matches tag"
          fi

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          architecture: x64
          distribution: 'temurin'

      - name: Compile
        run: ./gradlew assemble

      - name: Tests
        run: ./gradlew check
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

      - name: Update name of build artifact
        run: |
          aname="nf-fuzzball-${{ env.PLUGIN_VERSION }}-stable-${{ env.FUZZBALL_VERSION }}.zip"
          echo "Renaming build artifact to ${aname}"
          mv build/distributions/nf-fuzzball-*.zip build/distributions/${aname}

      - name: Create or update release and attach artifact
        if: github.ref_type == 'tag' && (github.event_name == 'push' || github.event.inputs.publish_release == 'true')
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.PLUGIN_VERSION }}
          tag: ${{ env.PLUGIN_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: "build/distributions/nf-fuzzball-${{ env.PLUGIN_VERSION }}-stable-${{ env.FUZZBALL_VERSION }}.zip"
          artifactContentType: "application/zip"
